	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DARKNESS_ENERGY             ; $07
	const DOUBLE_COLORLESS_ENERGY     ; $08
	const BULBASAUR                   ; $09
	const IVYSAUR                     ; $0a
	const VENUSAUR_LV64               ; $0b
	const VENUSAUR_LV67               ; $0c
	const CATERPIE                    ; $0d
	const METAPOD                     ; $0e
	const BUTTERFREE                  ; $0f
	const WEEDLE                      ; $10
	const KAKUNA                      ; $11
	const BEEDRILL                    ; $12
	const EKANS                       ; $13
	const ARBOK                       ; $14
	const NIDORANF                    ; $15
	const NIDORINA                    ; $16
	const NIDOQUEEN                   ; $17
	const NIDORANM                    ; $18
	const NIDORINO                    ; $19
	const NIDOKING                    ; $1a
	const ZUBAT                       ; $1b
	const GOLBAT                      ; $1c
	const ODDISH                      ; $1d
	const GLOOM                       ; $1e
	const VILEPLUME                   ; $1f
	const PARAS                       ; $20
	const PARASECT                    ; $21
	const VENONAT                     ; $22
	const VENOMOTH                    ; $23
	const BELLSPROUT                  ; $24
	const WEEPINBELL                  ; $25
	const VICTREEBEL                  ; $26
	const GRIMER                      ; $27
	const MUK                         ; $28
	const EXEGGCUTE                   ; $29
	const EXEGGUTOR                   ; $2a
	const KOFFING                     ; $2b
	const WEEZING                     ; $2c
	const TANGELA_LV8                 ; $2d
	const TANGELA_LV12                ; $2e
	const SCYTHER                     ; $2f
	const PINSIR                      ; $30
	const CHARMANDER                  ; $31
	const CHARMELEON                  ; $32
	const CHARIZARD                   ; $33
	const VULPIX                      ; $34
	const NINETALES_LV32              ; $35
	const NINETALES_LV35              ; $36
	const GROWLITHE                   ; $37
	const ARCANINE_LV34               ; $38
	const ARCANINE_LV45               ; $39
	const PONYTA                      ; $3a
	const RAPIDASH                    ; $3b
	const MAGMAR_LV24                 ; $3c
	const MAGMAR_LV31                 ; $3d
	const FLAREON_LV22                ; $3e
	const FLAREON_LV28                ; $3f
	const MOLTRES_LV35                ; $40
	const MOLTRES_LV37                ; $41
	const SQUIRTLE                    ; $42
	const WARTORTLE                   ; $43
	const BLASTOISE                   ; $44
	const PSYDUCK                     ; $45
	const GOLDUCK                     ; $46
	const POLIWAG                     ; $47
	const POLIWHIRL                   ; $48
	const POLIWRATH                   ; $49
	const TENTACOOL                   ; $4a
	const TENTACRUEL                  ; $4b
	const SEEL                        ; $4c
	const DEWGONG                     ; $4d
	const SHELLDER                    ; $4e
	const CLOYSTER                    ; $4f
	const KRABBY                      ; $50
	const KINGLER                     ; $51
	const HORSEA                      ; $52
	const SEADRA                      ; $53
	const GOLDEEN                     ; $54
	const SEAKING                     ; $55
	const STARYU                      ; $56
	const STARMIE                     ; $57
	const MAGIKARP                    ; $58
	const GYARADOS                    ; $59
	const LAPRAS                      ; $5a
	const VAPOREON_LV29               ; $5b
	const VAPOREON_LV42               ; $5c
	const OMANYTE                     ; $5d
	const OMASTAR                     ; $5e
	const ARTICUNO_LV35               ; $5f
	const ARTICUNO_LV37               ; $60
	const PIKACHU_LV12                ; $61
	const PIKACHU_LV16                ; $62
	const PIKACHU_ALT_LV16            ; $63
	const FLYING_PIKACHU              ; $64
	const SURFING_PIKACHU_LV13        ; $65
	const RAICHU_LV35                 ; $66
	const RAICHU_LV40                 ; $67
	const RAICHU_LV45                 ; $68
	const MAGNEMITE_LV13              ; $69
	const MAGNEMITE_LV15              ; $6a
	const MAGNETON_LV28               ; $6b
	const MAGNETON_LV35               ; $6c
	const VOLTORB                     ; $6d
	const ELECTRODE_LV35              ; $6e
	const ELECTRODE_LV42              ; $6f
	const ELECTABUZZ_LV20             ; $70
	const ELECTABUZZ_LV35             ; $71
	const JOLTEON_LV24                ; $72
	const JOLTEON_LV29                ; $73
	const ZAPDOS_LV40                 ; $74
	const ZAPDOS_LV64                 ; $75
	const ZAPDOS_LV68                 ; $76
	const SANDSHREW                   ; $77
	const SANDSLASH                   ; $78
	const DIGLETT                     ; $79
	const DUGTRIO                     ; $7a
	const MANKEY                      ; $7b
	const PRIMEAPE                    ; $7c
	const MACHOP                      ; $7d
	const MACHOKE                     ; $7e
	const MACHAMP                     ; $7f
	const GEODUDE                     ; $80
	const GRAVELER                    ; $81
	const GOLEM                       ; $82
	const ONIX                        ; $83
	const CUBONE                      ; $84
	const MAROWAK_LV26                ; $85
	const MAROWAK_LV32                ; $86
	const HITMONLEE                   ; $87
	const HITMONCHAN                  ; $88
	const RHYHORN                     ; $89
	const RHYDON                      ; $8a
	const KABUTO                      ; $8b
	const KABUTOPS                    ; $8c
	const AERODACTYL                  ; $8d
	const ABRA                        ; $8e
	const KADABRA                     ; $8f
	const ALAKAZAM                    ; $90
	const SLOWPOKE_LV9                ; $91
	const SLOWPOKE_LV18               ; $92
	const SLOWBRO                     ; $93
	const GASTLY_LV8                  ; $94
	const GASTLY_LV17                 ; $95
	const HAUNTER_LV17                ; $96
	const HAUNTER_LV22                ; $97
	const GENGAR                      ; $98
	const DROWZEE                     ; $99
	const HYPNO                       ; $9a
	const MR_MIME                     ; $9b
	const JYNX                        ; $9c
	const MEWTWO_LV53                 ; $9d
	const MEWTWO_LV60                 ; $9e
	const MEWTWO_ALT_LV60             ; $9f
	const MEW_LV8                     ; $a0
	const MEW_LV15                    ; $a1
	const MEW_LV23                    ; $a2
	const PIDGEY                      ; $a3
	const PIDGEOTTO                   ; $a4
	const PIDGEOT_LV38                ; $a5
	const PIDGEOT_LV40                ; $a6
	const RATTATA                     ; $a7
	const RATICATE                    ; $a8
	const SPEAROW                     ; $a9
	const FEAROW                      ; $aa
	const CLEFAIRY                    ; $ab
	const CLEFABLE                    ; $ac
	const JIGGLYPUFF_LV12             ; $ad
	const JIGGLYPUFF_LV13             ; $ae
	const JIGGLYPUFF_LV14             ; $af
	const WIGGLYTUFF                  ; $b0
	const MEOWTH_LV14                 ; $b1
	const MEOWTH_LV15                 ; $b2
	const PERSIAN                     ; $b3
	const FARFETCHD                   ; $b4
	const DODUO                       ; $b5
	const DODRIO                      ; $b6
	const LICKITUNG                   ; $b7
	const CHANSEY                     ; $b8
	const KANGASKHAN                  ; $b9
	const TAUROS                      ; $ba
	const DITTO                       ; $bb
	const EEVEE                       ; $bc
	const PORYGON                     ; $bd
	const SNORLAX                     ; $be
	const DRATINI                     ; $bf
	const DRAGONAIR                   ; $c0
	const DRAGONITE_LV41              ; $c1
	const DRAGONITE_LV45              ; $c2
	const PROFESSOR_OAK               ; $c3
	const IMPOSTER_PROFESSOR_OAK      ; $c4
	const BILL                        ; $c5
	const MR_FUJI                     ; $c6
	const LASS                        ; $c7
	const IMAKUNI_CARD                ; $c8
	const POKEMON_TRADER              ; $c9
	const POKEMON_BREEDER             ; $ca
	const CLEFAIRY_DOLL               ; $cb
	const MYSTERIOUS_FOSSIL           ; $cc
	const ENERGY_RETRIEVAL            ; $cd
	const ENERGY_RECYCLER             ; $ce
	const ENERGY_SEARCH               ; $cf
	const ENERGY_REMOVAL              ; $d0
	const ENERGY_SWITCH               ; $d1
	const SWITCH                      ; $d2
	const POKEMON_CENTER              ; $d3
	const POKE_BALL                   ; $d4
	const SCOOP_UP                    ; $d5
	const COMPUTER_SEARCH             ; $d6
	const POKEDEX                     ; $d7
	const PLUSPOWER                   ; $d8
	const DEFENDER                    ; $d9
	const ITEM_FINDER                 ; $da
	const GIOVANNI                    ; $db
	const DEVOLUTION_SPRAY            ; $dc
	const POTION                      ; $dd
	const SUPER_POTION                ; $de
	const FULL_HEAL                   ; $df
	const REVIVE                      ; $e0
	const MAINTENANCE                 ; $e1
	const POKEMON_FLUTE               ; $e2
	const GAMBLER                     ; $e3
	const RECYCLE                     ; $e4
	const RARE_CANDY                  ; $e5
DEF NUM_CARDS EQU const_value - 1

DEF ENERGY_IDS_START  EQU GRASS_ENERGY
DEF POKEMON_IDS_START EQU BULBASAUR
DEF TRAINER_IDS_START EQU PROFESSOR_OAK
